# Generated automatically from Makefile.in by configure.


CFLAGS = -g -O2
CC = gcc
LIBS = -lm 
AIR5LIB = src/libRPW.a

all: library align_warp alignlinear binarize binarymask binarymath cd_air cd_warp combine_air combine_warp crop definecommon_air determinant_mask fixheader fuse gsmooth identify invert_air layout magnify makeaheader manualreslice mv_air mv_warp overlay_mask reconcile_air reorient resize reslice reslice_ucf reslice_unwarp reslice_unwarp_ucf reslice_vector reslice_warp reslice_warp_ucf reunite scan_vector scan_warp scanair scanheader separate setheadermax sizeof softmean softmeannorescale straightmean straightmeannorescale strictmean strictmeannorescale zoomer

library:
	cd src; ${MAKE} libRPW.a "CFLAGS=${CFLAGS}"

align_warp: ${AIR5LIB} align_warp.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
alignlinear: ${AIR5LIB} alignlinear.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
binarize: ${AIR5LIB} binarize.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
binarymask: ${AIR5LIB} binarymask.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
binarymath: ${AIR5LIB} binarymath.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
cd_air: ${AIR5LIB} cd_air.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
cd_warp: ${AIR5LIB} cd_warp.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
combine_air: ${AIR5LIB} combine_air.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
combine_warp: ${AIR5LIB} combine_warp.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
crop: ${AIR5LIB} crop.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
definecommon_air: ${AIR5LIB} definecommon_air.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
determinant_mask: ${AIR5LIB} determinant_mask.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
fixheader: ${AIR5LIB} fixheader.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
fuse: ${AIR5LIB} fuse.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
gsmooth: ${AIR5LIB} gsmooth.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
identify: ${AIR5LIB} identify.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
invert_air: ${AIR5LIB} invert_air.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
layout: ${AIR5LIB} layout.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
magnify: ${AIR5LIB} magnify.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
makeaheader: ${AIR5LIB} makeaheader.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
manualreslice: ${AIR5LIB} manualreslice.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
mv_air: ${AIR5LIB} mv_air.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
mv_warp: ${AIR5LIB} mv_warp.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
overlay_mask: ${AIR5LIB} overlay_mask.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reconcile_air: ${AIR5LIB} reconcile_air.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reorient: ${AIR5LIB} reorient.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
resize: ${AIR5LIB} resize.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice: ${AIR5LIB} reslice.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice_ucf: ${AIR5LIB} reslice_ucf.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice_unwarp: ${AIR5LIB} reslice_unwarp.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice_unwarp_ucf: ${AIR5LIB} reslice_unwarp_ucf.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice_vector: ${AIR5LIB} reslice_vector.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice_warp: ${AIR5LIB} reslice_warp.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice_warp_ucf: ${AIR5LIB} reslice_warp_ucf.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reunite: ${AIR5LIB} reunite.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
scan_vector: ${AIR5LIB} scan_vector.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
scan_warp: ${AIR5LIB} scan_warp.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
scanair: ${AIR5LIB} scanair.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
scanheader: ${AIR5LIB} scanheader.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
separate: ${AIR5LIB} separate.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
setheadermax: ${AIR5LIB} setheadermax.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
sizeof: ${AIR5LIB} sizeof.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
softmean: ${AIR5LIB} softmean.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
softmeannorescale: ${AIR5LIB} softmeannorescale.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
straightmean: ${AIR5LIB} straightmean.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
straightmeannorescale: ${AIR5LIB} straightmeannorescale.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
strictmean: ${AIR5LIB} strictmean.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
strictmeannorescale: ${AIR5LIB} strictmeannorescale.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
zoomer: ${AIR5LIB} zoomer.c
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}

.c :
	${CC} $@.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
	
clean:
	cd src; ${MAKE} clean
	rm -f align_warp alignlinear binarize binarymask binarymath cd_air cd_warp combine_air combine_warp crop definecommon_air determinant_mask fixheader fuse gsmooth identify invert_air layout magnify makeaheader manualreslice mv_air mv_warp overlay_mask reconcile_air reorient resize reslice reslice_ucf reslice_unwarp reslice_unwarp_ucf reslice_vector reslice_warp reslice_warp_ucf reunite scan_vector scan_warp scanair scanheader separate setheadermax sizeof softmean softmeannorescale straightmean straightmeannorescale strictmean strictmeannorescale zoomer
	rm -f config.cache config.log config.status
	cd bin; rm -f align_warp alignlinear binarize binarymask binarymath cd_air cd_warp combine_air combine_warp crop definecommon_air determinant_mask fixheader fuse gsmooth identify invert_air layout magnify makeaheader manualreslice mv_air mv_warp overlay_mask reconcile_air reorient resize reslice reslice_ucf reslice_unwarp reslice_unwarp_ucf reslice_vector reslice_warp reslice_warp_ucf reunite scan_vector scan_warp scanair scanheader separate setheadermax sizeof softmean softmeannorescale straightmean straightmeannorescale strictmean strictmeannorescale zoomer

	
install:
	mv align_warp alignlinear binarize binarymask binarymath cd_air cd_warp combine_air combine_warp crop definecommon_air determinant_mask fixheader fuse gsmooth identify invert_air layout magnify makeaheader manualreslice mv_air mv_warp overlay_mask reconcile_air reorient resize reslice reslice_ucf reslice_unwarp reslice_unwarp_ucf reslice_vector reslice_warp reslice_warp_ucf reunite scan_vector scan_warp scanair scanheader separate setheadermax sizeof softmean softmeannorescale straightmean straightmeannorescale strictmean strictmeannorescale zoomer bin
	
distclean:
	cd src; ${MAKE} distclean
	rm -f align_warp alignlinear binarize binarymask binarymath cd_air cd_warp combine_air combine_warp crop definecommon_air determinant_mask fixheader fuse gsmooth identify invert_air layout magnify makeaheader manualreslice mv_air mv_warp overlay_mask reconcile_air reorient resize reslice reslice_ucf reslice_unwarp reslice_unwarp_ucf reslice_vector reslice_warp reslice_warp_ucf reunite scan_vector scan_warp scanair scanheader separate setheadermax sizeof softmean softmeannorescale straightmean straightmeannorescale strictmean strictmeannorescale zoomer
	rm -f config.cache config.log config.status
	rm -f Makefile
	cd bin; rm -f align_warp alignlinear binarize binarymask binarymath cd_air cd_warp combine_air combine_warp crop definecommon_air determinant_mask fixheader fuse gsmooth identify invert_air layout magnify makeaheader manualreslice mv_air mv_warp overlay_mask reconcile_air reorient resize reslice reslice_ucf reslice_unwarp reslice_unwarp_ucf reslice_vector reslice_warp reslice_warp_ucf reunite scan_vector scan_warp scanair scanheader separate setheadermax sizeof softmean softmeannorescale straightmean straightmeannorescale strictmean strictmeannorescale zoomer
	
	

