.TH tal_smooth Brainvox
.SH NAME
tal_smooth \- Performs gaussian smoothing on a volume.
.SH SYNOPSIS
tal_smooth [options] inputtemp outputtemp
.SH DESCRIPTION
This program smoothes the input volume by convolving it with a
gaussian filter.  This filter sigma value is selected such that the
FWHM of the filter occurs at the extent of the x dimension radius.
Individual radii can be specified in each dimension.
.PP
INPUTTEMP is the input volume template.  OUTPUTTEMP is the 
volume template for the output smoothed volume.
.PP
Options:
.TP
-x(dx)
The x axis size of the image in pixels.  The default is 256 pixels.
.TP
-y(dy)
The y axis size of the image in pixels.  The default is 256 pixels.
.TP
-z(dz)
The image depth in bytes.  The default is 2 bytes (unsigned shorts).
.TP
-o(offset)
16 bit data offset.  All 16 bit data have this offset value added before
the data is used.  The default is -256.
.TP
-f(start)
This specifies the slice number for the first image in the volume.  Default:1.
.TP
-l(end)
This specifies the slice number for the last image in the volume.  Default:15.
.TP
-i(step)
This specifies the increment number to go from one slice to the next.  Default:1.
.TP
-b
This specifies that 16bit images should be byte swapped before using.
.TP
-v
This enables verbose mode.  In verbose mode, the coefficient values for the
gaussian kernal are output to standard output in the kernal form that can be
used by tal_stat.
.TP
-r(dx[:dy:dz])
This option sets the radius for the gaussian kernal.  When only a single value is specified
'-r(dx)' the size of the kernal in x, y, and z is uniform and is dx pixels.  When the form
'-rdx:dy:dz' is used, the kernal size is specified separately in all dimensions.  The default
is: 7:7:7.
.TP
-m(masktemp)
This option selects a filename template for a mask volume.  If a mask volume is specified,
output smoothed values are computed only for those voxels which are inside the mask
volume (mask voxel > 0).  The default: no masking is performed.
.TP
-d(back)
This option selects the background value to be output outside of the mask.
The default value is:0.0.
.PP
.SH SEE ALSO
tal_programs, tal_stat
.SH NOTES
Currently, the FWHM of the kernal is selected by the x dimension radius when differing
radii are specified and the spherical kernal is simply truncated early or extended in other
dimensions.  Future
versions will implement true ellipsoidal kernals for differing FWHM in each dimension.
.PP
When a mask volume is specified, the mask is used to select which output voxels the
convolution is to be computed for.  Voxels used in the convolution (not at the same
coordinate as the output voxel) are not clipped to the mask volume.
.PP
When smoothing to a particular FWHM value, the output volume FWHM is equal to the
square root of the squares of the input volume FWHM and the gaussian filter FWHM.
.SH ORIGIN
Brainvox, Human Neuroanatomy and Neuroimaging Lab, Department of Neurology,
University of Iowa
