.TH tal_pca Brainvox
.SH NAME
tal_pca \- Computes the principle components of a series of volumes, considering each pixel as an input component.
.SH SYNOPSIS
tal_pca [options] ncomponents [-|vol1temp ...]
.SH DESCRIPTION
This program computes a number of principle components specified on the 
command line by NCOMPONENTS.  This is done via singular value decomposition 
(SVD) of the intput data.  Each input volume is considered a row of the
matrix to be decomposed (one observation) with each pixel in the volume
being one component of the observation (a column of the matrix).
.PP
The N requested Eigen values are output on standard output, followed by the
projection of each input volume's data (observation) on each principle 
component (dot product of the Eigen vector and the observation vector).  
The output is one row per input volume with one column for each Eigen vector.
These projections can be analyzed externally, or used as intput data to
a regression analysis (tal_regress).
Eigen vectors can also be output as volumes and viewed separately.
.PP
Filename templates of all the input volumes are specified on the command line.
If a "-" is used for the input volume template, the input volume template names
are read from stdin.  A volume mask may be used to restrict the operation to a
portion of the volume and step options (-i and -s) exist to reduce the
computation to a managable size.
.PP
Options:
.TP
-x(dx)
The x axis size of the image in pixels.  The default is 256 pixels.
.TP
-y(dy)
The y axis size of the image in pixels.  The default is 256 pixels.
.TP
-z(dz)
The image depth in bytes.  All input volume must have the same depth.
The default is 4 bytes (floats).
.TP
-f(start)
This specifies the slice number for the first image in the volume.  Default:1.
.TP
-l(end)
This specifies the slice number for the last image in the volume.  Default:119.
.TP
-i(step)
This specifies the increment number to go from one slice to the next.  
Default:2.
.TP
-s(skip)
This specifies the step factor for pixels in the XY plane. 
Default:2.
.TP
-b
This specifies that 16bit images should be byte swapped before using.  
Default: no swapping.
.TP
-v[v[v[v]]]
This option specifies a verbosity level (number of v's).  Not presently useful.
.TP
-o(offset)
This option specifies an offset value added to each pixel before it is used. 
Default:0.
.TP
-c
This option enables variable centering.  The mean of each column of data is
removed before the decomposition is performed.  The projections are of these
centered variables if this option is enabled.  Default: no centering.
.TP
-p(projfile)
Output the projection of the input data on each principle component and
write to the file PROJFILE.  Default:stdout.
.TP
-O(num):(outvoltemp)
This option specifies that the Eigen vector specified by NUM be saved to
disk as a volume using the volume template OUTVOLTEMP.  If stepping factors
were specified greater than one, the output images will be pixel replicated
to fill in the skipped areas.
The volume is a floating point volume.  Default: do not save.
.TP
-m(masktemp)
This option allows the user to specify a filename template for a mask
volume.  Statistics are only computed for voxels withing this volume.  The
default is to compute for all voxels.
.SH SEE ALSO
tal_programs, tal_math, tal_regress
.SH NOTES
This program requires that ALL observations be memory resident to operate.
It also requires that two times this amount of memory be available.  The
step options (-i and -s) can be used to decimate large volumes to meet
local memory requirements.  Note: pixels outside of the mask are NOT stored,
thus a tighter mask can be used to reduce the step factors.
.PP
tal_pca uses singular value decomposition based on the LINPACK ZSVDC
routine:
Dongarra JJ, Bunch JR, Moler CB, and Stewart GW, LINPACK User's Guide,
SIAM, Philadelphia, 1979.
.PP
Currently, only 8bit mask volume are supported.
.SH ORIGIN
Brainvox, Human Neuroanatomy and Neuroimaging Lab, Department of Neurology,
University of Iowa
