MODULE cvio_reg
DESCRIPTION CVIO Regression DLM
VERSION 1.0
SOURCE Univ of Iowa, Department of Neurology
BUILD_DATE  8 Oct 2000
FUNCTION	REG_CREATE	2	3
FUNCTION	REG_DESTROY	1	1
FUNCTION	REG_ADD_OBS	3	4
FUNCTION	REG_REMOVE_OBS	3	4
FUNCTION	REG_CALC_SS	5	6
FUNCTION	REG_CALC_COEF	2	3	KEYWORDS
