.TH cvio_ls 1
.SH NAME
cvio_ls - list CVIO shared memory files
.SH SYNOPSIS
cvio_ls [options]
.SH DESCRIPTION
The program lists the names of all the shared memory CVIO files
currently in the host's memory.
.PP
Options:
.TP
-v
Selects verbose mode
.PP
.SH SEE ALSO
cvio_intro(1)
.SH NOTES
.SH ORIGIN
Brainvox, Human Neuroanatomy and Neuroimaging Lab, Department of Neurology,
University of Iowa
