.TH cvio_info 1
.SH NAME
cvio_info - display header information from CVIO files
.SH SYNOPSIS
cvio_info file [files...]
.SH DESCRIPTION
This program reads the headers from a number of CVIO files and
prints the results to stdout.  All attributes, required and
user are output.
.SH SEE ALSO
cvio_intro(1), cvio_attr(1)
.SH NOTES
.SH ORIGIN
Brainvox, Human Neuroanatomy and Neuroimaging Lab, Department of Neurology,
University of Iowa
