.TH cvio_rm 1
.SH NAME
cvio_rm - remove CVIO files
.SH SYNOPSIS
cvio_rm [options] file [file...]
.SH DESCRIPTION
This program simply deletes an existing CVIO file from disk or 
from shared memory.  It will automatically delete all three files,
[rom the name of the header file.
.PP
Options:
.TP
-v
Selects verbose mode
.PP
.SH SEE ALSO
cvio_intro(1)
.SH NOTES
.SH ORIGIN
Brainvox, Human Neuroanatomy and Neuroimaging Lab, Department of Neurology,
University of Iowa
