***************************************************
*    Resource file converted to include by rmaker *
*    Source file:resedituif.r                     *
*    File contained:    11 dialog(s).             *
*    Compiled at:Fri Jun 21 14:48:39 1991         *
**Includes*****************************************
       Integer*4 newfile             
       Parameter (newfile              =     3) 
       Integer*4 openfile            
       Parameter (openfile             =     4) 
       Integer*4 savefile            
       Parameter (savefile             =     5) 
       Integer*4 appendfile          
       Parameter (appendfile           =     6) 
       Integer*4 quit                
       Parameter (quit                 =     7) 
       Integer*4 windowtext          
       Parameter (windowtext           =     9) 
       Integer*4 itemtext2           
       Parameter (itemtext2            =    10) 
       Integer*4 itemtext            
       Parameter (itemtext             =    11) 
       Integer*4 typemenu            
       Parameter (typemenu             =    15) 
       Integer*4 gridmenu            
       Parameter (gridmenu             =    16) 
       Integer*4 objnummenu          
       Parameter (objnummenu           =    17) 
       Integer*4 popbutton           
       Parameter (popbutton            =    18) 
       Integer*4 pushbutton          
       Parameter (pushbutton           =    19) 
       Integer*4 shownumchk          
       Parameter (shownumchk           =    20) 
       Integer*4 xitemchk            
       Parameter (xitemchk             =    21) 
       Integer*4 newitem             
       Parameter (newitem              =    22) 
       Integer*4 deleteitem          
       Parameter (deleteitem           =    23) 
       Integer*4 labeledit           
       Parameter (labeledit            =    25) 
       Integer*4 boxframed           
       Parameter (boxframed            =     3) 
       Integer*4 boxfilled           
       Parameter (boxfilled            =     4) 
       Integer*4 boxcolor            
       Parameter (boxcolor             =     5) 
       Integer*4 textitem            
       Parameter (textitem             =     4) 
       Integer*4 textclickable       
       Parameter (textclickable        =     5) 
       Integer*4 textframed          
       Parameter (textframed           =     6) 
       Integer*4 texthighlighted     
       Parameter (texthighlighted      =     7) 
       Integer*4 textfont            
       Parameter (textfont             =     8) 
       Integer*4 textjustify         
       Parameter (textjustify          =     9) 
       Integer*4 editframed          
       Parameter (editframed           =     5) 
       Integer*4 editfont            
       Parameter (editfont             =     6) 
       Integer*4 sbaredits           
       Parameter (sbaredits            =     7) 
