#ifdef CAP_NOUS
#define viewpo_  VIEWPO
#define pushvi_  PUSHVI
#define popvie_  POPVIE
#define ortho_   ORTHO
#define ortho2_  ORTHO2
#define gfflush_ GFFLUSH
#define gflush_  GFLUSH
#define resetl_  RESETL
#define rectzo_  RECTZO
#define zdraw_   ZDRAW
#define lrectr_  LRECTR
#define lrectw_  LRECTW
#define readso_  READSO
#define rectre_  RECTRE
#define rectwr_  RECTWR
#define writem_  WRITEM
#define zclear_  ZCLEAR
#define linewi_  LINEWI
#define bgnpoi_  BGNPOI
#define endpoi_  ENDPOI
#define getmco_  GETMCO
#define wmpack_  WMPACK
#define zwrite_  ZWRITE
#define zfunct_  ZFUNCT
#define lsetde_  LSETDE
#define stenci_  STENCI
#define sclear_  SCLEAR
#define stensi_  STENSI
#define getvie_  GETVIE
#define getbuf_  GETBUF
#define frontb_  FRONTB
#define backbu_  BACKBU
#define zbuffe_  ZBUFFE
#define swapbu_  SWAPBU
#define getzbu_  GETZBU
#define deflin_  DEFLIN
#define setlin_  SETLIN
#define sboxfi_  SBOXFI
#define cmov2i_  CMOV2I
#define color_   COLOR
#define circfi_  CIRCFI
#define circi_   CIRCI
#define c3i_     C3I
#define recti_   RECTI
#define rectfi_  RECTFI
#define bgnclo_  BGNCLO
#define endclo_  ENDCLO
#define bgnlin_  BGNLIN
#define endlin_  ENDLIN
#define bgnpol_  BGNPOL
#define endpol_  ENDPOL
#define v2i_     V2I
#define v2f_     V2F
#define v2d_     V2D
#define v3d_     V3D
#define v3i_     V3I
#define cpack_   CPACK
#define clear_   CLEAR
#define rgbcol_  RGBCOL
#define depthc_  DEPTHC
#define lrgbra_  LRGBRA
#define guibtn_  GUIBTN
#define qdevic_  QDEVIC
#define qenter_  QENTER
#define qread_   QREAD
#define getval_  GETVAL
#define getbut_  GETBUT
#define qreset_  QRESET
#define	noise_   NOISE
#define qtest_   QTEST
#define freepu_  FREEPU
#define newpup_  NEWPUP
#define addtop_  ADDTOP
#define change_  CHANGE
#define setpup_  SETPUP
#define dopup2_  DOPUP2
#define dopup_   DOPUP
#define getdes_  GETDES
#define strwid_  STRWID
#define gethei_  GETHEI
#define charst_  CHARST
#define winico_  WINICO
#define wincon_  WINCON
#define	winget_  WINGET
#define winset_  WINSET
#define wintit_  WINTIT
#define reshap_  RESHAP
#define getori_  GETORI
#define	getsiz_  GETSIZ
#define minsiz_  MINSIZ
#define winope_  WINOPE
#define winclo_  WINCLO
#define foregr_  FOREGR
#define rgbmod_  RGBMOD
#define doubleb_ DOUBLEB
#define single_  SINGLE
#define gconfi_  GCONFI
#define getdis_  GETDIS
#define getgde_  GETGDE
#define mapcol_  MAPCOL
#define ringbe_  RINGBE
#define prefpo_  PREFPO
#define prefpo2_ PREFPO2
#define prefsi_  PREFSI
#define srand_   SRAND
#endif
