
	Integer*4	SCR_CMD_NONE
	Parameter	(SCR_CMD_NONE = 0)
	Integer*4	SCR_CMD_ROT
	Parameter	(SCR_CMD_ROT = 1)
	Integer*4	SCR_CMD_COLOR
	Parameter	(SCR_CMD_COLOR = 2)
	Integer*4	SCR_CMD_PAL
	Parameter	(SCR_CMD_PAL = 3)
	Integer*4	SCR_CMD_FILTER
	Parameter	(SCR_CMD_FILTER = 4)
	Integer*4	SCR_CMD_RENDER
	Parameter	(SCR_CMD_RENDER = 5)
	Integer*4	SCR_CMD_HWRENDER
	Parameter	(SCR_CMD_HWRENDER = 9)
	Integer*4	SCR_CMD_AUTORENDER
	Parameter	(SCR_CMD_AUTORENDER = 10)
	Integer*4	SCR_CMD_TEXRENDER
	Parameter	(SCR_CMD_TEXRENDER = 11)
	Integer*4	SCR_CMD_REBOUND
	Parameter	(SCR_CMD_REBOUND = 12)
	Integer*4	SCR_CMD_SAVE
	Parameter	(SCR_CMD_SAVE = 6)
	Integer*4	SCR_CMD_DATA
	Parameter	(SCR_CMD_DATA = 7)
	Integer*4	SCR_CMD_LIGHTING
	Parameter	(SCR_CMD_LIGHTING = 8)

