C
C	Define the brainvox_voxel colors
C
	Integer*4	BV_COLOR_BLACK
	Integer*4	BV_COLOR_RED
	Integer*4	BV_COLOR_GREEN
	Integer*4	BV_COLOR_YELLOW
	Integer*4	BV_COLOR_BLUE
	Integer*4	BV_COLOR_MAGENTA
	Integer*4	BV_COLOR_CYAN
	Integer*4	BV_COLOR_WHITE
	Integer*4	BV_COLOR_CORAL
	Integer*4	BV_COLOR_CHARTRE
	Integer*4	BV_COLOR_SPGREEN
	Integer*4	BV_COLOR_SLATEBL
	Integer*4	BV_COLOR_BLUEVIO
	Integer*4	BV_COLOR_ORANGER

	Parameter	(BV_COLOR_BLACK		= 0)
	Parameter	(BV_COLOR_RED		= 1)
	Parameter	(BV_COLOR_GREEN		= 2)
	Parameter	(BV_COLOR_YELLOW	= 3)
	Parameter	(BV_COLOR_BLUE		= 4)
	Parameter	(BV_COLOR_MAGENTA	= 5)
	Parameter	(BV_COLOR_CYAN		= 6)
	Parameter	(BV_COLOR_WHITE		= 7)
	Parameter	(BV_COLOR_CORAL		= 8)
	Parameter	(BV_COLOR_CHARTRE	= 9)
	Parameter	(BV_COLOR_SPGREEN	= 10)
	Parameter	(BV_COLOR_SLATEBL	= 11)
	Parameter	(BV_COLOR_BLUEVIO	= 12)
	Parameter	(BV_COLOR_ORANGER	= 13)
