import os

env = Environment(ENV = {'PATH' : os.environ['PATH']})

# Define paths
source_dir = 'source'
build_dir = 'build/html'

# Command to run sphinx-build
sphinx_cmd = f'sphinx-build -a -E -b html docs/{source_dir} docs/{build_dir}'

# Create a target to run the build
# 'source/conf.py' ensures rebuilds if configuration changes
html_docs = env.Command(build_dir, env.Dir(source_dir).glob('*.rst') + ['source/conf.py'], sphinx_cmd)

env.Clean(source_dir, "build")
