#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "geom_view_io.h"
#include "glm.h"

/*
 * $Id: geom_view_io.c 1677 2006-03-07 04:26:40Z rjfrank $
 */


long int write_OBJ_file(char *file,long int nverts,long int ntris,
	float *verts,float *norms,long int *tris)
{
	FILE 	*fp;
	int	i;

        if (strcmp(file,"-") == 0) {
                fp = stdout;
        } else {
                fp = fopen(file,"w");
		if (!fp) return(1);
	}

	fprintf(fp,"#\n");
	fprintf(fp,"# Wavefront OBJ generated by tal_programs\n");
	fprintf(fp,"#\n");

	fprintf(fp,"# %ld vertices\n",nverts);
        for(i=0;i<nverts;i++) {
        	fprintf(fp,"v %f %f %f\n",
                           verts[i*3+0], verts[i*3+1], verts[i*3+2]);
	}

	fprintf(fp,"# %ld normals\n",nverts);
        for(i=0;i<nverts;i++) {
        	fprintf(fp,"vn %f %f %f\n",
                           norms[i*3+0], norms[i*3+1], norms[i*3+2]);
	}

	fprintf(fp,"# %ld faces\n",ntris);
        for(i=0;i<ntris;i++) {
        	fprintf(fp,"f %ld//%ld %ld//%ld %ld//%ld\n",
                           tris[i*3+0]+1, tris[i*3+0]+1, tris[i*3+1]+1,
                           tris[i*3+1]+1, tris[i*3+2]+1, tris[i*3+2]+1);
	}

	fprintf(fp,"\n");

	if (fp != stdout) fclose(fp);

	return(0);
}

long int read_OBJ_file(char *file,long int *nverts,long int *ntris,
	float **verts,float **norms,long int **tris)
{
	GLMmodel *o;
	GLMgroup *g;
	int n;

	o = glmReadOBJ(file);
	if (!o) return(1);
	
	*nverts = o->numvertices;
	*verts = (float *)malloc(o->numvertices*sizeof(float)*3);
	if (!*verts) {
		glmDelete(o);
		return(1);
	}
	memcpy(*verts,o->vertices+3,o->numvertices*sizeof(float)*3);

	if (!o->normals) glmVertexNormals(o,90.0);
	*norms = (float *)malloc(o->numvertices*sizeof(float)*3);
	if (!*norms) {
		free(*verts);
		glmDelete(o);
		return(1);
	}
	memcpy(*norms,o->normals+3,o->numvertices*sizeof(float)*3);

	n = 0;
	g = o->groups;
	while(g) {
		n += g->numtriangles;
		g = g->next;
	}

	*tris = (long int *)malloc(n*sizeof(long int)*3);
	if (!*tris) {
		free(*verts);
		free(*norms);
		glmDelete(o);
		return(1);
	}
        *ntris = n;

	n = 0;
	g = o->groups;
	while(g) {
	    int i;
  	    for(i=0;i<g->numtriangles;i++) {
		(*tris)[n++] = o->triangles[g->triangles[i]].vindices[0]-1;
		(*tris)[n++] = o->triangles[g->triangles[i]].vindices[1]-1;
		(*tris)[n++] = o->triangles[g->triangles[i]].vindices[2]-1;
    	    }
	    g = g->next;
	}

	glmDelete(o);

	return(0);
}

#define TAL_GEO_COMMENT "# TAL_PROGRAMS Geomview file 1.0"

long int write_geom_file(char *file,long int nverts,long int ntris,
	float *verts,float *norms,long int *tris)
{
	FILE 		*fp;
	long int	i;

        if (strcmp(file,"-") == 0) {
                fp = stdout;
        } else {
                fp = fopen(file,"w");
		if (fp == 0L) return(1);
	}
	fprintf(fp,"%s\n",TAL_GEO_COMMENT);

        fprintf(fp,"%s\n","NOFF");
        fprintf(fp,"%ld %ld %ld\n",nverts,ntris,0L);

	for(i=0;i<nverts;i++) {
		fprintf(fp,"%f %f %f ",verts[(i*3)],verts[(i*3)+1],
			verts[(i*3)+2]);
		fprintf(fp,"%f %f %f\n",norms[(i*3)],norms[(i*3)+1],
			norms[(i*3)+2]);
	}
	for(i=0;i<ntris;i++) {
		fprintf(fp,"%ld %ld %ld %ld\n",3L,tris[(i*3)],tris[(i*3)+1],
			tris[(i*3)+2]);
	}

	if (fp != stdout) fclose(fp);

	return(0);
}

long int read_geom_file(char *file,long int *nverts,long int *ntris,
	float **verts,float **norms,long int **tris)
{
	FILE 		*fp;
	char		tstr[256];
	long int	retval = 1;
	long int	i,dummy,j;

        if (strcmp(file,"-") == 0) {
                fp = stdin;
        } else {
                fp = fopen(file,"r");
		if (fp == 0L) return(1);
	}
/* header */
	i = 0;
	while(fgets(tstr,256,fp)) {
		if (strstr(tstr,TAL_GEO_COMMENT)!=0){
			i = 1;
			break;
		}
	}
	if (i == 0) goto err_exit;
/* NOFF */
	fgets(tstr,256,fp);
	if (strstr(tstr,"NOFF") == 0) goto err_exit;
/* vals */
	fgets(tstr,256,fp);
	sscanf(tstr,"%ld %ld %ld",nverts,ntris,&dummy);
	if ((*nverts == 0) || (*ntris == 0)) goto err_exit;

/* here we go */
	*verts = (float *)malloc((*nverts)*sizeof(float)*3);
	if (*verts == 0L) goto err_exit;
	*norms = (float *)malloc((*nverts)*sizeof(float)*3);
	if (*verts == 0L) {
		free(*verts);
		goto err_exit;
	}
	*tris = (long int *)malloc((*ntris)*sizeof(long int)*3);
	if (*verts == 0L) {
		free(*verts);
		free(*norms);
		goto err_exit;
	}

/* read em */
	j = 0;
	for(i=0;i<(*nverts);i++) {
		fgets(tstr,256,fp);
		sscanf(tstr,"%f %f %f %f %f %f",
			&((*verts)[j]),&((*verts)[j+1]),&((*verts)[j+2]),
			&((*norms)[j]),&((*norms)[j+1]),&((*norms)[j+2]));
		j += 3;
	}
	j = 0;
	for(i=0;i<(*ntris);i++) {
		fgets(tstr,256,fp);
		sscanf(tstr,"%ld %ld %ld %ld",&dummy,
			&((*tris)[j]),&((*tris)[j+1]),&((*tris)[j+2]));
		j += 3;
	}
	
	retval = 0; /* success */

err_exit:
	if (fp != stdin) fclose(fp);

	return(retval);
}

