import os
import os.path
import platform
import subprocess

include_dirs = ['.', 'zlib', 'fftn']
libs = ['libtal_zlib']
lib_dirs = ['.']
defines = ['USE_ZLIB']
shared_libs = []
if platform.system() == 'Windows':
    defines += ['WIN32', '_WIN32', '_CRT_SECURE_NO_WARNINGS']
    include_dirs += ['../freeglut/include']
    lib_dirs += ['../freeglut/lib/x64']
    libs += ['freeglut']
    shared_libs += ['../freeglut/bin/x64/freeglut.dll']

env = Environment(CPPPATH=include_dirs, CPPDEFINES=defines,
                  LIBS=libs, LIBPATH=lib_dirs)

# Mingw toolchain
#   tools=['mingw']

# Intel compiler bits
#    CC='icx-cl',    # Use Windows-style C compiler
#    CXX='icx-cl',   # Use Windows-style C++ compiler
#    LINK='icx-cl', 
#    ENV = {'PATH' : os.environ['PATH'], 'TMP' : os.environ['TMP']})

zlib_src = ["zlib/adler32.c", "zlib/compress.c", "zlib/crc32.c", 
            "zlib/gzio.c", "zlib/deflate.c", "zlib/trees.c", "zlib/zutil.c", 
            "zlib/inflate.c", "zlib/infblock.c", "zlib/inftrees.c", "zlib/infcodes.c", 
            "zlib/infutil.c", "zlib/inffast.c", "zlib/uncompr.c"]

common_src = ["fileio.c", "name_changer.c", "roi_utils.c", "polyfill_c.c", 
              "nifti1.c", "tal_shm_interface.c", "conversion.c"]

progs = []
progs += env.StaticLibrary('libtal_math', source=common_src+['tal_math.c', 'macro.c', 'macro2c.c'])
progs += env.StaticLibrary('libtal_stat', source=common_src+['tal_stat.c', 'macro.c', 'macro2c.c'])
env.StaticLibrary('libtal_zlib', source=zlib_src)

progs += env.Program('tal_resample', source=common_src + ["tal_resample.c"])
progs += env.Program('tal_normalize', source=common_src + ["tal_normalize.c"])
progs += env.Program('tal_merge', source=common_src + ["tal_merge.c"])
progs += env.Program('tal_smooth', source=common_src + ["tal_smooth.c"])
progs += env.Program('tal_CDA', source=common_src + ["tal_CDA.c", "stats.c"])
progs += env.Program('tal_centroid', source=common_src + ["tal_centroid.c"])
progs += env.Program('tal_cutting', source=common_src + ["tal_cutting.c"])
progs += env.Program('tal_roi_sample', source=common_src + ["tal_roi_sample.c"])
# Same binary, two names
progs += env.Program('analyze2raw', source=common_src + ["convert_analyze.c"])
progs += env.Program('raw2analyze', source=common_src + ["convert_analyze.c"])
progs += env.Program('tal_probe', source=common_src + ["tal_probe.c"])
progs += env.Program('tal_math', source=["tal_math_link.c"], LIBS=libs + ['libtal_math'])
progs += env.Program('tal_histcheck', source=common_src + ["tal_histcheck.c", "stats.c"])
progs += env.Program('tal_stat', source=["tal_stat_link.c"], LIBS=libs + ['libtal_stat'])
progs += env.Program('tal_cluster', source=common_src + ["tal_cluster.c"])
progs += env.Program('tal_euler', source=common_src + ["tal_euler.c"])
progs += env.Program('tal_sphere', source=common_src + ["tal_sphere.c"])
progs += env.Program('worsley', source=common_src + ["worsley.c", "stats.c"])
progs += env.Program('tal_regress', source=common_src + ["tal_regress.c", "regress_parse.c", "regress_one.c", "274.c", "75_base.c"])
# Same binary, three names
progs += env.Program('tal_edm', source=common_src + ["tal_skel_edm.c", "skeleton2d.c", "skeleton3d.c", "label_comp.c"])
progs += env.Program('tal_skel', source=common_src + ["tal_skel_edm.c", "skeleton2d.c", "skeleton3d.c", "label_comp.c"])
progs += env.Program('tal_label', source=common_src + ["tal_skel_edm.c", "skeleton2d.c", "skeleton3d.c", "label_comp.c"])
progs += env.Program('tal_rad_sample', source=common_src + ["tal_rad_sample.c"])
progs += env.Program('tal_standardize', source=common_src + ["tal_standardize.c", "stats.c"])
progs += env.Program('tal_rerandom', source=common_src + ["tal_rerandom.c", "stats.c"])
progs += env.Program('tal_spatial', source=common_src + ["tal_spatial.c", "stats.c"])
progs += env.Program('tal_surface', source=common_src + ["tal_surface.c", "iso_contour.c"])
progs += env.Program('tal_remask', source=common_src + ["tal_remask.c", "autotrace.c"])
progs += env.Program('tal_mrinorm', source=common_src + ["tal_mrinorm.c", "274.c", "75_base.c"])
progs += env.Program('tal_resize', source=common_src + ["tal_resize.c", "crop_volume.c"])
progs += env.Program('tal_ls', source=common_src + ["tal_ls.c"])
progs += env.Program('tal_fft', source=common_src + ["tal_fft.c", "fftn.c"])
progs += env.Program('tal_median', source=common_src + ["tal_median.c", "stats.c"])
progs += env.Program('tal_rename', source=common_src + ["tal_rename.c"])
progs += env.Program('tal_pca', source=common_src + ["tal_pca.c", "svd.c"])
progs += env.Program('tal_ortho', source=common_src + ["tal_ortho.c"])
progs += env.Program('tal_roi2mesh', source=common_src + ["tal_roi2mesh.c", "glm.c", "geom_view_io.c"])
progs += env.Program('tal_optimal', source=common_src + ["tal_optimal.c", "opt_search.c"])
progs += env.Program('tal_mcubes', source=common_src + ["tal_mcubes.c", "iso_contour.c", "glm.c", "geom_view_io.c"])
progs += env.Program('tal_thinmesh', source=common_src + ["tal_ortho.c", "iso_trim.c", "glm.c", "geom_view_io.c"])
progs += env.Program('tal_trace', source=common_src + ["tal_trace.c", "autotrace.c"])
# Same binary, two names
progs += env.Program('tal_rmshm', source=common_src + ["tal_shmem.c"])
progs += env.Program('tal_mkshm', source=common_src + ["tal_shmem.c"])
progs += env.Program('tal_warp', source=common_src + ["tal_warp.c"])
progs += env.Program('tal_gwcsf', source=common_src + ["tal_gwcsf.c", "274.c", "75_base.c", "skeleton3d.c", "autotrace.c", "tal_nrc.c"])
progs += env.Program('tal_prandom', source=common_src + ["tal_prandom.c", "stats.c"])
progs += env.Program('tal_pts2vol', source=common_src + ["tal_pts2vol.c"])
progs += env.Program('tal_rft', source=common_src + ["tal_rft.c", "stats.c"])
progs += env.Program('tal_nifti', source=common_src + ["tal_nifti.c"])

progs += env.Program('tal_vbin', source=common_src + ["tal_vbin.c"])
    
# Header generators
bld_skel = env.Program('build_3dskel', source=['build_3dskel.c'])
bld_iso = env.Program('make_isotab', source=['make_isotab.c'])

def bld_skel_hdr(target, source, env):
    app = str(bld_skel[0])
    out = str(target[0])
    cmd = [app]
    print(f"Running {cmd}")
    try:
        with open(out, "w") as f:
            subprocess.run(cmd, stdout=f, text=True)
    except Exception as e:
        print("Error ",e)
    
def bld_iso_hdr(target, source, env):
    app = str(bld_iso[0])
    out = str(target[0])
    cmd = [app]
    print(f"Running {cmd}")
    try:
        with open(out, "w") as f:
            subprocess.run(cmd, stdout=f, text=True)
    except Exception as e:
        print("Error ",e)

env.Command("skel3d_etable.h", [], bld_skel_hdr)
env.Command("iso_tab.h", [], bld_iso_hdr)

env.Depends("skel3d_etable.h", bld_skel)
env.Depends("iso_tab.h", bld_iso)

# install the apps
target_dir = os.path.join(env.Dir('#').abspath, 'bin')
env.Install(target_dir, progs)
env.Install(target_dir, shared_libs)
